# clog project configuration
# This file should be committed to version control to share project identity with your team

uuid: ab81678f-6026-4164-8bac-6c1733ddb586
display_name: sandboxels
created_at: 2026-02-04T11:43:01.329850Z

